connect "SYS"/"&&sysPassword" as SYSDBA
set echo on
spool /media/storage/as/oracle/logs/cone/1.datafiles_init

ALTER DATABASE DATAFILE '/media/storage/as/oracle/data/master/undotbs01.dbf' RESIZE 10000M;
ALTER DATABASE DATAFILE '/media/storage/as/oracle/data/master/undotbs01.dbf' AUTOEXTEND ON  NEXT 1000M MAXSIZE UNLIMITED;

CREATE TABLESPACE E$CORE DATAFILE 
'/media/storage/as/oracle/data/master/ecore.dbf' SIZE 5000M AUTOEXTEND ON NEXT 100M MAXSIZE 5000M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 32K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE ROLE SESSION_MANAGER NOT IDENTIFIED;

CREATE USER CORE
IDENTIFIED BY VALUES '5C05D80DBA3D6FC2'
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT
ACCOUNT UNLOCK;


CREATE USER E$CORE
IDENTIFIED BY VALUES '7CD9C72DDA786401'
DEFAULT TABLESPACE E$CORE
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT
ACCOUNT UNLOCK;
-- 3 Roles for E$CORE 
GRANT DBA TO E$CORE WITH ADMIN OPTION;
GRANT CONNECT TO E$CORE WITH ADMIN OPTION;
GRANT SELECT_CATALOG_ROLE TO E$CORE WITH ADMIN OPTION;
ALTER USER E$CORE DEFAULT ROLE ALL;
-- 10 System Privileges for E$CORE 
GRANT CREATE ANY PROCEDURE TO E$CORE WITH ADMIN OPTION;
GRANT CREATE ANY SYNONYM TO E$CORE WITH ADMIN OPTION;
GRANT EXECUTE ANY PROCEDURE TO E$CORE;
GRANT DROP ANY PROCEDURE TO E$CORE WITH ADMIN OPTION;
GRANT CREATE USER TO E$CORE;
GRANT DROP ANY SYNONYM TO E$CORE WITH ADMIN OPTION;
GRANT ALTER USER TO E$CORE;
GRANT UNLIMITED TABLESPACE TO E$CORE WITH ADMIN OPTION;
GRANT CREATE ANY TABLE TO E$CORE WITH ADMIN OPTION;
GRANT DROP USER TO E$CORE;



CREATE USER E$XML
IDENTIFIED BY VALUES '84686A394D1A623F'
DEFAULT TABLESPACE E$CORE
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT
ACCOUNT UNLOCK;
-- 2 Roles for E$XML 
GRANT RESOURCE TO E$XML;
GRANT DBA TO E$XML;
ALTER USER E$XML DEFAULT ROLE ALL;
-- 3 System Privileges for E$XML 
GRANT UNLIMITED TABLESPACE TO E$XML;
GRANT CREATE ANY TABLE TO E$XML WITH ADMIN OPTION;
GRANT EXECUTE ANY PROCEDURE TO E$XML;



CREATE USER EDI_WEB
IDENTIFIED BY VALUES 'B6C08CD770D872FF'
DEFAULT TABLESPACE E$CORE
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT
ACCOUNT UNLOCK;
-- 1 Role for EDI_WEB 
GRANT CONNECT TO EDI_WEB;
ALTER USER EDI_WEB DEFAULT ROLE ALL;
-- 1 System Privilege for EDI_WEB 
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
PRIVILEGE    => 'MANAGE_ANY',
GRANTEE      => 'EDI_WEB',
ADMIN_OPTION => FALSE);
END;
/


spool off
