##MAIN
$IncludeConfig /media/sysdata/rev5/techpool/ontology/logitoring/in4_syslog/engine/internals/common_global.pre

#PRE_INIT CLIENT
$IncludeConfig /media/sysdata/rev5/techpool/ontology/logitoring/in4_syslog/engine/internals/common_client.pre

#RUN CLIENT
$IncludeConfig /media/sysdata/rev5/techpool/ontology/*/*/in4_*/_in4_syslog/*.client_parse
$IncludeConfig /media/sysdata/rev5/techpool/ontology/*/in4_*/_in4_syslog/*.client_parse

$IncludeConfig /media/sysdata/rev5/techpool/ontology/logitoring/in4_syslog/engine/internals/client_parse/*.conf
$IncludeConfig /media/sysdata/rev5/techpool/ontology/logitoring/in4_syslog/engine/internals/client_parse/*.post
