connect "SYS"/"&&sysPassword" as SYSDBA
set echo on
spool /media/storage/as/oracle/logs/create_db/zabbix.log
 CREATE USER MONITORING
  IDENTIFIED BY !monitoring1
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT ALTER SESSION TO MONITORING;
  GRANT CREATE SESSION TO MONITORING;
  GRANT CONNECT TO MONITORING;
  ALTER USER MONITORING DEFAULT ROLE ALL;
  GRANT SELECT ON V_$INSTANCE TO MONITORING;
  GRANT SELECT ON DBA_USERS TO MONITORING;
  GRANT SELECT ON V_$LOG_HISTORY TO MONITORING;
  GRANT SELECT ON V_$PARAMETER TO MONITORING;
  GRANT SELECT ON SYS.DBA_AUDIT_SESSION TO MONITORING;
  GRANT SELECT ON V_$LOCK TO MONITORING;
  GRANT SELECT ON DBA_REGISTRY TO MONITORING;
  GRANT SELECT ON V_$LIBRARYCACHE TO MONITORING;
  GRANT SELECT ON V_$SYSSTAT TO MONITORING;
  GRANT SELECT ON V_$PARAMETER TO MONITORING;
  GRANT SELECT ON V_$LATCH TO MONITORING;
  GRANT SELECT ON V_$PGASTAT TO MONITORING;
  GRANT SELECT ON V_$SGASTAT TO MONITORING;
  GRANT SELECT ON V_$LIBRARYCACHE TO MONITORING;
  GRANT SELECT ON V_$PROCESS TO MONITORING;
  GRANT SELECT ON DBA_DATA_FILES TO MONITORING;
  GRANT SELECT ON DBA_TEMP_FILES TO MONITORING;
  GRANT SELECT ON DBA_FREE_SPACE TO MONITORING;
  GRANT SELECT ON V_$SYSTEM_EVENT TO MONITORING;
spool off  
