set serveroutput on;

DECLARE
  RetVal BINARY_INTEGER;
  Rt BINARY_INTEGER;
  vl BINARY_INTEGER;
  VLL BINARY_INTEGER;
  BOTH_WORDS VARCHAR2(200) := 'XXX789989XXX';
  ERRORSTR VARCHAR2(20) := '         ';
  fdt TIMESTAMP;
BEGIN
  fdt := SYSTIMESTAMP;
END;
/
--quit
