#!/bin/bash
GitRepoStable="https://github.com/conecenter/cho.git"
GitRepoDev="https://github.com/eistomin/cho.git"
GitPath="/media/sysdata/in4/cho"
VmDiskLoopSystem="loop250"
VmDiskLoopSysdata="loop251"
VmDiskSizeSystem="1500m"
VmDiskSizeSysdata="400m"
VmDiskSizeSwap="50m"
