###
### NEW
## ALTER SYSTEM SET UNDO_RETENTION = 10;
## DROP TABLESPACE SSPRO INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
## DROP USER SSPRO CASCADE;
## 
###
set oracle_home=C:\oracle\product\10.2.0\db_1

C:\oracle\product\10.2.0\db_1\BIN\exp SSPRO/224328@SST owner=SSPRO statistics=none file=SSPRO.dmp log=SSPRO.log
C:\oracle\product\10.2.0\db_1\BIN\exp DISPATCH/224328@SST owner=DISPATCH statistics=none file=DISPATCH.dmp log=DISPATCH.log
###

ALTER DATABASE DATAFILE '/media/storage/database/oracle/lapro/data/main/undotbs01.dbf' AUTOEXTEND ON  NEXT 1000M MAXSIZE UNLIMITED;


CREATE TABLESPACE DISPATCH DATAFILE '/media/storage/database/oracle/lapro/data/main/dispatch.dbf' SIZE 1000M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 32K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE LAPRO DATAFILE '/media/storage/database/oracle/lapro/data/main/lapro.dbf' SIZE 1000M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 32K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;



CREATE TABLESPACE SSPRO DATAFILE '/media/storage/database/oracle/lapro/data/main/sspro.dbf' SIZE 1000M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 32K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE USER SSPRO
  IDENTIFIED BY qwe123
  DEFAULT TABLESPACE SSPRO
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 3 Roles for SSPRO 
  GRANT IMP_FULL_DATABASE TO SSPRO WITH ADMIN OPTION;
  GRANT CONNECT TO SSPRO WITH ADMIN OPTION;
  GRANT DBA TO SSPRO WITH ADMIN OPTION;
  ALTER USER SSPRO DEFAULT ROLE ALL;

  


CREATE USER SSPRO_EMPLOYEE
  IDENTIFIED BY qwe123
  DEFAULT TABLESPACE SSPRO
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Role for SSPRO_EMPLOYEE 
  GRANT CONNECT TO SSPRO_EMPLOYEE;
  ALTER USER SSPRO_EMPLOYEE DEFAULT ROLE NONE;
  -- 1 System Privilege for SSPRO_EMPLOYEE 
  GRANT CREATE SESSION TO SSPRO_EMPLOYEE;
  
  
  
  

CREATE USER DISPATCH
  IDENTIFIED BY qwe123
  DEFAULT TABLESPACE DISPATCH
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for DISPATCH 
  GRANT CONNECT TO DISPATCH WITH ADMIN OPTION;
  GRANT DBA TO DISPATCH WITH ADMIN OPTION;
  ALTER USER DISPATCH DEFAULT ROLE ALL;

  -- 4 System Privileges for DISPATCH 
  GRANT SELECT ANY TABLE TO DISPATCH WITH ADMIN OPTION;
  GRANT UNLIMITED TABLESPACE TO DISPATCH WITH ADMIN OPTION;
  GRANT CREATE SESSION TO DISPATCH WITH ADMIN OPTION;
  GRANT SELECT ANY DICTIONARY TO DISPATCH WITH ADMIN OPTION;
  
  
  
  
  CREATE USER LAPRO
  IDENTIFIED BY qwe123
  DEFAULT TABLESPACE LAPRO
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 5 Roles for LAPRO 
  GRANT SELECT_CATALOG_ROLE TO LAPRO WITH ADMIN OPTION;
  GRANT CONNECT TO LAPRO WITH ADMIN OPTION;
  GRANT DBA TO LAPRO WITH ADMIN OPTION;
  GRANT IMP_FULL_DATABASE TO LAPRO WITH ADMIN OPTION;
  GRANT EXECUTE_CATALOG_ROLE TO LAPRO WITH ADMIN OPTION;
  ALTER USER LAPRO DEFAULT ROLE CONNECT, DBA, IMP_FULL_DATABASE, EXECUTE_CATALOG_ROLE;
  -- 13 System Privileges for LAPRO 
  GRANT CREATE ANY SEQUENCE TO LAPRO WITH ADMIN OPTION;
  GRANT CREATE ANY PROCEDURE TO LAPRO WITH ADMIN OPTION;
  GRANT CREATE ANY VIEW TO LAPRO WITH ADMIN OPTION;
  GRANT CREATE TABLE TO LAPRO WITH ADMIN OPTION;
  GRANT SELECT ANY SEQUENCE TO LAPRO WITH ADMIN OPTION;
  GRANT SELECT ANY TABLE TO LAPRO WITH ADMIN OPTION;
  GRANT CREATE PROCEDURE TO LAPRO WITH ADMIN OPTION;
  GRANT CREATE ROLE TO LAPRO WITH ADMIN OPTION;
  GRANT CREATE DATABASE LINK TO LAPRO WITH ADMIN OPTION;
  GRANT CREATE ANY INDEX TO LAPRO WITH ADMIN OPTION;
  GRANT UNLIMITED TABLESPACE TO LAPRO WITH ADMIN OPTION;
  GRANT CREATE SEQUENCE TO LAPRO WITH ADMIN OPTION;
  GRANT CREATE SESSION TO LAPRO WITH ADMIN OPTION;
  -- 1 Tablespace Quota for LAPRO 
  ALTER USER LAPRO QUOTA UNLIMITED ON LAPRO;  

  
CREATE USER LAPRO_EMPLOYEE
  IDENTIFIED BY qwe123
  DEFAULT TABLESPACE LAPRO
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Role for SSPRO_EMPLOYEE 
  GRANT CONNECT TO LAPRO_EMPLOYEE;
  ALTER USER LAPRO_EMPLOYEE DEFAULT ROLE NONE;
  -- 1 System Privilege for SSPRO_EMPLOYEE 
  GRANT CREATE SESSION TO LAPRO_EMPLOYEE;  
  
  
  
1) DISPATCH 	- imp dispatch/qwe123 FILE=DISPATCH.dmp FUll=y log=dispatch.log
  
2) SSPRO 		- imp sspro/qwe123 FILE=SSPRO.dmp FUll=y log=sspro.log
  
  
  
  
  
    GRANT EXECUTE ON DISPATCH.Z_AUTH TO SSPRO_EMPLOYEE;
    GRANT SELECT ON DISPATCH.Z_STATFILT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.AGREEMENT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.AGREEMENT_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.AGREEM_RATE TO SSPRO_EMPLOYEE;
    GRANT SELECT, FLASHBACK ON SSPRO.AGRITEM TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.AGRITEM_DAY_HIST TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.AGRITEM_M TO SSPRO_EMPLOYEE;
    GRANT SELECT, FLASHBACK ON SSPRO.BL TO SSPRO_EMPLOYEE;
    GRANT SELECT, FLASHBACK ON SSPRO.BLITEM TO SSPRO_EMPLOYEE;
    GRANT SELECT, FLASHBACK ON SSPRO.BLITEM_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.BLITEM_PASSENGER TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.BLITEM_STATUS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.BL_ADDRESS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.BL_ADDRESS_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.BL_GODSNUMMER TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.BL_HAULAGE TO SSPRO_EMPLOYEE;
    GRANT SELECT, FLASHBACK ON SSPRO.BL_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.BL_OCEAN TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.BL_SHIPMENT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.BOOKING TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.BOOKITEM TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.BOOKITEM_IMO TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.BOOKITEM_LCL TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.BOOKITEM_LCL_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.BOOKITEM_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.BOOK_FIELDS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_ACCGROUP TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_ACCOUNT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_AGENT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_BANK TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_BASIS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_BOOK_FORMAT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_BOXOPER TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_CHAINS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_CLAIM TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_CNREASON TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_COMMOD TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_CONTACT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_CONTACT_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_COUNTRY TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_CURRENCY TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_DISB_FUEL TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_DISB_PCOST TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_DISB_VCOST TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_DIVISION TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_DOC TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_DRIVER TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_ECONOMY_ART TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_ECONOMY_TYPE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_EDI_EQUTYPE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_EINVOICE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_FREIGHT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_IMO TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_INVOICE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_KIND TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_LTAGREEMENT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_LTAGREEMENT_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_MEASURE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_MERCHANT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_MERCHANT_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_MERCHANT_U TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_PACKING TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_PASSENG TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_POINT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_RDOC TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_RELATION TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_REMIND TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_SASCO_RWO TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_SASCO_RWS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_SCS_FRW TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_SCS_FRW_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_TERMS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_TRAILER TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_TRANSP TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_VAT TO SSPRO_EMPLOYEE;
    GRANT SELECT, UPDATE ON SSPRO.CAT_VESSEL TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CAT_WH TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CREQUEST TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CREQUEST_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CURRATE_ACC_SYS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CURRATE_COMP TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CURRENCY_DAY_ACC_SYS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.CURRENCY_DAY_COMP TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.DAGREEMENT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.DEMURRAGE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.DISB_ADDCOST TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.DISB_BUNKER TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.DISB_COMISSION TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.DISB_COMISSION_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.DISB_DEF_PORTCOST TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.DISB_DEF_VOYCOST TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.DISB_PORTCOST TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.DISB_PORT_PREL TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.DISB_ROUTECOST TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.DISB_STEVEDOR TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.DISB_STEVEDOR_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.DISB_VOYCOST TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.DISB_VOY_COMISSION TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.DISB_VOY_PREL TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.DISB_VOY_STEV TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.DOC TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.DOCITEM TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.DOCITEM_FIELDS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.DOCITEM_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.DOC_FIELDS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.DOC_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.DOC_RULE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.EQUIPMENT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.EQUIPMENT_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.EQUIPMENT_MOVE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.EQUIPMENT_MOVE_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.EQUIPMENT_STATUS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.EQUIP_INFO TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.EQUIP_INSPECTION TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.EQUIP_REDELIVERY TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.EQUIP_REDELIVERY_U TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.EQUIP_SO_MOVE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.EQU_AGREEMENT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.EQU_AGRITEM TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.EQU_OFFHIRE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.EQU_OFFHIRE_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.EQU_REFERENCE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.EQU_REFERENCE_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.ESTIMATE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.EXPINV TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.EXPREC TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.FORECAST TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.FOREDEF TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.FOREWEEK TO SSPRO_EMPLOYEE;
    GRANT SELECT, FLASHBACK ON SSPRO.FREIGHT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.FREIGHT_HISTORY TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.FREIGHT_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.FREIGHT_VERSION TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.FWROUTE TO SSPRO_EMPLOYEE;
    GRANT EXECUTE ON SSPRO.GET_INTEGER_IN_WORDS TO SSPRO_EMPLOYEE;
    GRANT SELECT, FLASHBACK ON SSPRO.IMO TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.IMO_TEMPLATE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.INC_ESTIMATE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.INVOICE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.INVOICE_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.INVOICE_RATE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.INVOICE_U TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.INVPREC TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.INVREC TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.INVREC_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.INVREC_U TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.INV_COMPRESSED TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.INV_COMPRESSED_U TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.JLR_IMPORT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.JLR_MESSAGE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.JLR_MODELS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.JLR_STOCK TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.JLR_VEHICLES TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.JOB TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.JOBITEM TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.JOBITEM_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.JOB_FREIGHT TO SSPRO_EMPLOYEE;
    GRANT SELECT, UPDATE ON SSPRO.JOB_HEAD TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.JOB_HEAD_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.JOB_LIABILITY TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.JOB_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.JOB_ROUTES TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_ACC_MERCHANT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_AGREEM_AGENT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_AGREEM_BILLING TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_AGREEM_BOXOPER TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_AGREEM_DCLIENT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_AGREEM_DEMUR TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_AGREEM_FORMAT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_AGREEM_INFO TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_AGREEM_MEASURE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_AGREEM_QUOTA TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_AGREEM_SERVICE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_AGRITEM_DEMAGR TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_AGR_FRTERM TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_AGR_MEASURE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_AGR_TOTERM TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_BANK_ACCOUNTS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_BLITEM_BLITEM TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_BLITEM_CABOTAGE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_BLITEM_CHAINS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_BLITEM_COUNTRY TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_BLITEM_DSC TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_BLITEM_DSC_U TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_BLITEM_E_DO TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_BLITEM_INFO TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_BLITEM_MANNCT TO SSPRO_EMPLOYEE;
    GRANT SELECT, FLASHBACK ON SSPRO.LINK_BLITEM_MEASURE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_BLITEM_PASSENG TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_BLITEM_PORTCALL TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_BLITEM_SCSINF2 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_BLITEM_SCSINFO TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_BL_AGENT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_BL_AG_PAYMENT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_BL_DELIVERY TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_BL_EXPREC TO SSPRO_EMPLOYEE;
    GRANT SELECT, FLASHBACK ON SSPRO.LINK_BL_INFO TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_BL_MANNCT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_BOOKITEM_INFO TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_CATDOC_DEPART TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_CATDOC_SERVICE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_CATFR_CATINV TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_CATINV_CATFR TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_CATINV_DIVISION TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_CN_REASON TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_COMISS_COMMOD TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_COMISS_SERV TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_COMMOD_COMMOD TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_COMMOD_DECK TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_COMMOD_MEAS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_COMMOD_PACK TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_CURR_ASYS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_DAGREEM_PORT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_DOC_BL TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_DOC_JOB TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_DRULE_DOCKIND TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_DRULE_SERVICE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_EQUIP_DAMAGE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_EQUIP_PARAM TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_EQUIP_SUBLEASE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_EQUREF_EQUIP TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_EQUREF_POINTS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_EQUREF_SUBLEASE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_EQURENT_OPER TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_INVART_VATART TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_INVOICE_PUB TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_INVREC_BLITEM TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_INVREC_INVREC TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_INVREC_JOBITEM TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_INVREC_RW_BILL TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_INVREC_TR_LEG TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_INV_BL TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_INV_EXPREC TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_INV_INV TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_INV_JOB TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_INV_RW_JOB TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_INV_TR_JOB TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_JHEAD_COST TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_JHEAD_EXPREC TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_JHEAD_INCOME TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_JHEAD_INV TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_JHEAD_JOB TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_JHEAD_MARGIN TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_JHEAD_NOTCLOSED TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_JLRVEH_BLITEM TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_JLRVEH_MESSAGE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_JLRVEH_STOCK TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_JOB_EXPREC TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_LCL_BLIT_BLIT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_LINE_SERVICE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_MANIFEST_MEAS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_MANNCL_AGR TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_MAN_LEG TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_MERCHANT_RUSER TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_POINT_UNAME TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_PORTCALL_AGENT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_PORTCALL_MAIL TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_PORTCALL_TERM TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_PORT_AGENT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_PORT_DEPOT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_PORT_MERCHANT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_PORT_TERM TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_RDOC_AGENT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_RD_EQUIP TO SSPRO_EMPLOYEE;
    GRANT SELECT, UPDATE ON SSPRO.LINK_RELATION_FILE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_RELATION_JHEAD TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_REMIND_USER TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT, UPDATE ON SSPRO.LINK_REQUEST_FILE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_SASCO_EA_POINT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_SASCO_EI_RENT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_SASCO_EQUIPMENT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_SASCO_MERCHANT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_SCS_BLITEM_PLP TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_SCS_BL_MES TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_SCS_BL_PLP TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_SERVICE_TERM TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_STEV_COMMOD TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_TARDEM_PORT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_TARIFF_ASYS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_TARIFF_SERVICE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_TARIFF_TERMS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_TARLIN_COMMOD TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_TINV_INV TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_USER_AGENT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_USER_DIVISION TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_USER_MERCHANT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_USER_SERVICE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_USER_USER TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_VOYAGE_AGENT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_VOYAGE_CHECK TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_WHINSTR_EQUIP TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_WH_INSTRUCT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_WH_INSTRUCT_U TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.LINK_WH_PORT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.MANIFEST TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.MANN_EDICARGO TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.MANN_FORD_CLIENT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.MANN_JLR_XML TO SSPRO_EMPLOYEE;
    GRANT EXECUTE ON SSPRO.MANN_SERV TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.MAN_APPROVE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.MAN_APPROVE_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.MAN_BL_CHECKSUM TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.MAN_SBI_INVOICE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.MERCHANT_ADDRESS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.MERCHANT_ADDRESS_U TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.MES_COMMOD TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.MES_QUOTATION TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.NAVIRAIL_NOT_ALLOWED TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.NTV_CAT_THEME TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.NTV_CHANNEL TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.NTV_CHECK TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.NTV_EFIR TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.NTV_EFIR_U TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.NTV_FILM TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.NTV_FILMKIND TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.NTV_FILM_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.NTV_FILM_U TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.NTV_LINK_THEME_CHAN TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.PAY_INVOICE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.PORTCALL TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.PORTCHAINS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.QUOTATION TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.QUOTATION_FREIGHT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.QUOTATION_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.QUOTATION_U TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.QUOTA_RATE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.RELATION TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.RELATION_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.RUS_COMMOD TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.RUS_CONTACT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.RUS_COUNTRY TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.RUS_MERCHANT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.RUS_MERCHANT_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.RUS_MERCHANT_U TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.RUS_POINT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.RW_BILL TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.RW_BILL_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.RW_GNG_ETSNG TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.RW_JOB TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.RW_JOB_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.RW_LINK_B_PACKING TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.RW_LINK_B_PACKING2 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.RW_LINK_JOB_STATION TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.RW_MERCHANT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.RW_MERCHANT_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.RW_OWNER TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.RW_PACKING TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.RW_STATION TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.SASCO_ECONOMY TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.SASCO_ECONOMY_M TO SSPRO_EMPLOYEE;
    GRANT EXECUTE ON SSPRO.SASCO_SERV TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.SASCO_TEU_MONTH TO SSPRO_EMPLOYEE;
    GRANT EXECUTE ON SSPRO.SCS_SERV TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.SCS_XML_EQUIP_TMOVE TO SSPRO_EMPLOYEE;
    GRANT EXECUTE ON SSPRO.SERV TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.SERVICE TO SSPRO_EMPLOYEE;
    GRANT EXECUTE ON SSPRO.SET_TRANSFER TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.TARIFF_AGREEM TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.TARIFF_AGREEM_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.TARIFF_AGR_EST TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.TARIFF_AGR_HIST TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.TARIFF_AGR_HIST_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.TARIFF_DAGR TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.TARIFF_DEMUR TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.TARIFF_LINE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.TARIFF_LINE_M TO SSPRO_EMPLOYEE;
    GRANT EXECUTE ON SSPRO.TBL_SERV TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.TEST TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.TEST_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.TEST_U TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.TOT_INVOICE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.TR_EQUIPMENT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.TR_JOB TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.TR_JOB_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.TR_LEG TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.TR_LEG_U TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.TR_LINK_EXP_INVART TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.TSCHUDI_CLOSEJOB TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.TSCHUDI_DELETED_MAIL TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.TSCHUDI_LIAB_REFRESH TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.TSCHUDI_MERC_PROBLEM TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.TSCHUDI_MERGRECORDS TO SSPRO_EMPLOYEE;
    GRANT EXECUTE ON SSPRO.TSCHUDI_SERV TO SSPRO_EMPLOYEE;
    GRANT EXECUTE ON SSPRO.USER_ACCEPT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.USER_AGRITEM_MES TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.USER_AGRITEM_MES_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.USER_BLITEM_MES TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.USER_BLITEM_MES_M TO SSPRO_EMPLOYEE;
    GRANT EXECUTE ON SSPRO.USER_CONNECT TO SSPRO_EMPLOYEE;
    GRANT EXECUTE ON SSPRO.USER_LOGCHANNEL TO SSPRO_EMPLOYEE;
    GRANT EXECUTE ON SSPRO.USER_LOGSTAT TO SSPRO_EMPLOYEE;
    GRANT EXECUTE ON SSPRO.USER_LOGSTAT2 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.USER_QUOTA_MES TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.USER_QUOTA_MES_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.VOUCHER TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.VOYAGE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.VOYLEG TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.ZZ_BL TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.ZZ_FREIGHT_TARIFF TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.ZZ_JHEAD_ITEM TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.ZZ_KALLEMAIL TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.ZZ_LINK_JHEAD_DOC TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.ZZ_LINK_JHEAD_INV TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.ZZ_MANIFEST TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.ZZ_MERCHANT8 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.ZZ_SASCO_DAILY TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.ZZ_SCS_DAILY TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.ZZ_SCS_EQUIPMOVE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.ZZ_SCS_OVERBOOKING TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_ACC_SYSTEM TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_ADD_C TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_ADD_D TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_ADD_I TO SSPRO_EMPLOYEE;
    GRANT SELECT, FLASHBACK ON SSPRO.Z_ADD_M TO SSPRO_EMPLOYEE;
    GRANT SELECT, FLASHBACK ON SSPRO.Z_ADD_N TO SSPRO_EMPLOYEE;
    GRANT SELECT, FLASHBACK ON SSPRO.Z_ADD_S TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_ADD_T TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_ADD_U TO SSPRO_EMPLOYEE;
    GRANT EXECUTE ON SSPRO.Z_ADM TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_CAT_RULE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_CHANNEL TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_CLASS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_COLOR TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_COLOR_FRAGMENT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_COLOR_RULE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_COMPANY TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_COMP_OBJNAME TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_COUNTRY TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_DEL_DETAIL TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_DEL_STAT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_DEPART TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_ERROR TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_ERROR_U TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_EXP_ID TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_FIELD TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_FIELD_SEQ_START TO SSPRO_EMPLOYEE;
    GRANT ALTER, INSERT, SELECT, UPDATE ON SSPRO.Z_FILELIB TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_FORM TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_FORM_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_FORM_METHOD TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_DEL TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_DEL_STR TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_MERGE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_MERGE_ID TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_MERGE_STR TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_MOD1 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_MOD2 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_MOD3 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_MOD4 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_MOD5 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_MOD6 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_MOD7 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_MOD8 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_MOD9 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_MOD_STR1 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_MOD_STR2 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_MOD_STR3 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_MOD_STR4 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_MOD_STR5 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_MOD_STR6 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_MOD_STR7 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_MOD_STR8 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_MOD_STR9 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_MOD_U162 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_MOD_U163 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_MOD_U164 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_MOD_U165 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_MOD_U166 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_MOD_U167 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_MOD_U168 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_HISTORY_MOD_U169 TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_ID TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_INSLIST TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_JOB_LOG TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_JOB_LOG_STR TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_KIND_LIST TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_KIND_TYPE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_LANG_NUMBERS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_LINK_COMP_FORM TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_LINK_COMP_PAR TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_LINK_OBJ_FIELDS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_LINK_OBJ_USER TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_LINK_REP_FIELDS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_LINK_REP_REP TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_LINK_USER_DEP_ACC TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_LINK_USER_MENU TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_LINK_USER_REP TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_LINK_USER_TABLE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_LOGDELETE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_LOGSTAT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_LOGUPDATE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_MEMPAR TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_MENUS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_METHOD TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_MET_OBJECT TO SSPRO_EMPLOYEE;
    GRANT EXECUTE ON SSPRO.Z_MOD TO SSPRO_EMPLOYEE;
    GRANT EXECUTE ON SSPRO.Z_NEXTVAL TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_NOTES TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_OBJECT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_OBJECT_NAMES TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_OBJECT_RIGHTS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_OBJPROPDEF TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_OBJ_PROP TO SSPRO_EMPLOYEE;
    GRANT ALTER, SELECT ON SSPRO.Z_OPER TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_OPROPLIST TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_PACKING TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_PARAMS_DEF TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_PARAMS_VAL TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_PORTS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_PRINT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_PRINT_LOG TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_PROPERTY TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_PROPKIND TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_PROPVAL TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_REPORT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_REPORT_FIELD TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_REP_PICT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_REP_UNICODE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_SEQUENCE TO SSPRO_EMPLOYEE;
    GRANT EXECUTE ON SSPRO.Z_SEQ_NEXTVAL TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_STATFILT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_SUBST_FORM TO SSPRO_EMPLOYEE;
    GRANT EXECUTE ON SSPRO.Z_SYS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_TABINDEX TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_TABLE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_TAB_ARCRULE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_TEMP_RULE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_TIME_WORK TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_TRANSFER TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_TRANSFER_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_TRANS_ADDS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_TRANS_CATS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_TRANS_CLIENT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_TRANS_CODES TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_TRANS_FIELDS TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_TRANS_FUNC TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_TRANS_SCENARIO TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_TRANS_TABLES TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_TRANS_TABLES_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_U16_MESSAGES TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_USER TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_USER_EMAIL TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_USER_MESSAGE TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_USER_MESSAGE_U TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_USER_RULES TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_USER_RULES_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_VCX_METHOD TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_VCX_NAMES TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_WORK_JOURNAL TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_WORK_RECORD TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z_WORK_RECORD_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__AGREEMENT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__AGREEMENT_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__AGREEM_HISTORY TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__AGREEM_HISTORY_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__AGREEM_RATE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__AGRITEM TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__AGRITEM_DAY_HIST TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__AGRITEM_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__BL TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__BLITEM TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__BLITEM_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__BLITEM_PASSENGER TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__BLITEM_STATUS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__BL_ADDRESS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__BL_ADDRESS_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__BL_DISTRIB TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__BL_GODSNUMMER TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__BL_HAULAGE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__BL_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__BL_OCEAN TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__BL_SHIPMENT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__BOOKING TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__BOOKITEM TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__BOOKITEM_IMO TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__BOOKITEM_LCL TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__BOOKITEM_LCL_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__BOOKITEM_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__BOOK_FIELDS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_ACCGROUP TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_ACCOUNT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_AGENT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_BANK TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_BASIS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_BOOK_FORMAT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_BOXOPER TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_CHAINS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_CLAIM TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_CNREASON TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_COMMOD TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_CONTACT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_CONTACT_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_COUNTRY TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_CURRENCY TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_DISB_FUEL TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_DISB_PCOST TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_DISB_VCOST TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_DIVISION TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_DOC TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_DRIVER TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_ECONOMY_ART TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_ECONOMY_TYPE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_EDI_EQUTYPE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_EINVOICE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_FREIGHT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_IMO TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_INVOICE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_KIND TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_LTAGREEMENT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_LTAGREEMENT_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_MEASURE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_MERCHANT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_MERCHANT_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_MERCHANT_U TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_PACKING TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_PASSENG TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_POINT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_RDOC TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_RELATION TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_REMIND TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_SASCO_RWO TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_SASCO_RWS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_SCS_FRW TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_SCS_FRW_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_TERMS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_TRAILER TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_TRANSP TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_VAT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_VESSEL TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CAT_WH TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CREQUEST TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CREQUEST_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CURRATE_ACC_SYS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CURRATE_COMP TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CURRENCY_DAY_ACC_SYS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__CURRENCY_DAY_COMP TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__DAGREEMENT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__DEMURRAGE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__DISB_ADDCOST TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__DISB_BUNKER TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__DISB_COMISSION TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__DISB_COMISSION_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__DISB_DEF_PORTCOST TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__DISB_DEF_VOYCOST TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__DISB_PORTCOST TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__DISB_PORT_PREL TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__DISB_ROUTECOST TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__DISB_STEVEDOR TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__DISB_STEVEDOR_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__DISB_VOYCOST TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__DISB_VOY_COMISSION TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__DISB_VOY_PREL TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__DISB_VOY_STEV TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__DOC TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__DOCITEM TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__DOCITEM_FIELDS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__DOCITEM_FIELDS_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__DOCITEM_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__DOC_FIELDS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__DOC_FIELDS_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__DOC_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__DOC_RULE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__EQUIPMENT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__EQUIPMENT_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__EQUIPMENT_MOVE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__EQUIPMENT_MOVE_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__EQUIPMENT_STATUS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__EQUIP_INFO TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__EQUIP_INSPECTION TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__EQUIP_REDELIVERY TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__EQUIP_REDELIVERY_U TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__EQUIP_SO_MOVE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__EQU_AGREEMENT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__EQU_AGRITEM TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__EQU_OFFHIRE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__EQU_OFFHIRE_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__EQU_REFERENCE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__EQU_REFERENCE_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__ESTIMATE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__EXPINV TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__EXPREC TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__FORECAST TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__FOREDEF TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__FOREWEEK TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__FREIGHT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__FREIGHT_HISTORY TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__FREIGHT_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__FREIGHT_VERSION TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__FWROUTE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__IMO TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__IMO_TEMPLATE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__INC_ESTIMATE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__INVOICE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__INVOICE_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__INVOICE_RATE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__INVOICE_U TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__INVPREC TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__INVREC TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__INVREC_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__INVREC_U TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__INV_COMPRESSED TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__INV_COMPRESSED_U TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__JLR_IMPORT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__JLR_MESSAGE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__JLR_MODELS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__JLR_STOCK TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__JLR_VEHICLES TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__JOB TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__JOBITEM TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__JOBITEM_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__JOB_FREIGHT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__JOB_HEAD TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__JOB_HEAD_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__JOB_LIABILITY TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__JOB_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__JOB_ROUTES TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_ACC_MERCHANT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_AGREEM_AGENT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_AGREEM_BILLING TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_AGREEM_BOXOPER TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_AGREEM_DCLIENT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_AGREEM_DEMUR TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_AGREEM_FORMAT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_AGREEM_INFO TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_AGREEM_MEASURE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_AGREEM_QUOTA TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_AGREEM_SERVICE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_AGRITEM_DEMAGR TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_AGR_FRTERM TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_AGR_MEASURE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_AGR_TOTERM TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_BANK_ACCOUNTS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_BLITEM_BLITEM TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_BLITEM_CABOTAGE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_BLITEM_CHAINS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_BLITEM_COUNTRY TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_BLITEM_DSC TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_BLITEM_DSC_U TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_BLITEM_E_DO TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_BLITEM_INFO TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_BLITEM_MANNCT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_BLITEM_MEASURE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_BLITEM_PASSENG TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_BLITEM_PORTCALL TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_BLITEM_SCSINF2 TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_BLITEM_SCSINFO TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_BL_AGENT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_BL_AG_PAYMENT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_BL_DELIVERY TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_BL_EXPREC TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_BL_INFO TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_BL_MANNCT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_BOOKITEM_BLITEM TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_BOOKITEM_INFO TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_CATDOC_DEPART TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_CATDOC_SERVICE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_CATFR_CATINV TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_CATINV_CATFR TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_CATINV_DIVISION TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_CN_REASON TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_COMISS_COMMOD TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_COMISS_SERV TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_COMMOD_COMMOD TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_COMMOD_DECK TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_COMMOD_MEAS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_COMMOD_PACK TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_CURR_ASYS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_DAGREEM_PORT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_DOC_BL TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_DOC_JOB TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_DRULE_DOCKIND TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_DRULE_SERVICE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_EQUIP_DAMAGE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_EQUIP_PARAM TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_EQUIP_SUBLEASE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_EQUREF_EQUIP TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_EQUREF_POINTS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_EQUREF_SUBLEASE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_EQURENT_OPER TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_INVART_VATART TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_INVOICE_PUB TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_INVREC_BLITEM TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_INVREC_INVREC TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_INVREC_JOBITEM TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_INVREC_RW_BILL TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_INVREC_TR_LEG TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_INV_BL TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_INV_EXPREC TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_INV_INV TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_INV_JOB TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_INV_RW_JOB TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_INV_TR_JOB TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_JHEAD_COST TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_JHEAD_EXPREC TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_JHEAD_INCOME TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_JHEAD_INV TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_JHEAD_JOB TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_JHEAD_MARGIN TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_JHEAD_NOTCLOSED TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_JLRVEH_BLITEM TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_JLRVEH_MESSAGE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_JLRVEH_STOCK TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_JOB_EXPREC TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_LCL_BLIT_BLIT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_LINE_SERVICE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_MANIFEST_MEAS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_MANNCL_AGR TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_MAN_LEG TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_MERCHANT_RUSER TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_POINT_UNAME TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_PORTCALL_AGENT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_PORTCALL_MAIL TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_PORTCALL_TERM TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_PORT_AGENT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_PORT_DEPOT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_PORT_MERCHANT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_PORT_TERM TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_RDOC_AGENT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_RD_EQUIP TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_RELATION_FILE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_RELATION_JHEAD TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_REMIND_USER TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_REQUEST_FILE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_SASCO_EA_POINT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_SASCO_EI_RENT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_SASCO_EQUIPMENT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_SASCO_MERCHANT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_SCS_BLITEM_PLP TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_SCS_BL_MES TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_SCS_BL_PLP TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_SERVICE_TERM TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_STEV_COMMOD TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_TARDEM_PORT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_TARIFF_ASYS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_TARIFF_SERVICE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_TARIFF_TERMS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_TARLIN_COMMOD TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_TINV_INV TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_USER_AGENT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_USER_DIVISION TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_USER_MERCHANT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_USER_SERVICE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_USER_USER TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_VOYAGE_AGENT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_VOYAGE_CHECK TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_WHINSTR_EQUIP TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_WH_INSTRUCT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_WH_INSTRUCT_U TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__LINK_WH_PORT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__MANIFEST TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__MANN_EDICARGO TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__MANN_FORD_CLIENT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__MANN_JLR_XML TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__MAN_APPROVE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__MAN_APPROVE_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__MAN_BL_CHECKSUM TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__MAN_SBI_INVOICE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__MERCHANT_ADDRESS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__MERCHANT_ADDRESS_U TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__MES_COMMOD TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__MES_QUOTATION TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__NAVIRAIL_NOT_ALLOWED TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__NTV_CAT_THEME TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__NTV_CHANNEL TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__NTV_CHECK TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__NTV_EFIR TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__NTV_EFIR_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__NTV_EFIR_U TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__NTV_FILM TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__NTV_FILMKIND TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__NTV_FILM_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__NTV_FILM_U TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__NTV_LINK_THEME_CHAN TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__PAY_INVOICE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__PORTCALL TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__PORTCHAINS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__QUOTATION TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__QUOTATION_FREIGHT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__QUOTATION_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__QUOTATION_U TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__QUOTA_RATE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__RELATION TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__RELATION_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__REMINDER TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__REMINDER_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__RUS_COMMOD TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__RUS_CONTACT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__RUS_COUNTRY TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__RUS_MERCHANT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__RUS_MERCHANT_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__RUS_MERCHANT_U TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__RUS_POINT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__RW_BILL TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__RW_BILL_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__RW_BILL_U TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__RW_GNG_ETSNG TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__RW_JOB TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__RW_JOB_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__RW_JOB_U TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__RW_LINK_B_PACKING TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__RW_LINK_B_PACKING2 TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__RW_LINK_JOB_STATION TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__RW_MERCHANT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__RW_MERCHANT_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__RW_OWNER TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__RW_PACKING TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__RW_STATION TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__SASCO_ECONOMY TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__SASCO_ECONOMY_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__SASCO_TEU_MONTH TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__SCS_XML_EQUIP_TMOVE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__SERVICE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__TARIFF_AGREEM TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__TARIFF_AGREEM_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__TARIFF_AGR_EST TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__TARIFF_AGR_HIST TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__TARIFF_AGR_HIST_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__TARIFF_DAGR TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__TARIFF_DEMUR TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__TARIFF_HAULAGE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__TARIFF_LINE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__TARIFF_LINE_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__TEMP_RULE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__TEST TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__TEST_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__TEST_U TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__TOT_INVOICE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__TR_EQUIPMENT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__TR_JOB TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__TR_JOB_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__TR_LEG TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__TR_LEG_U TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__TR_LINK_EXP_INVART TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__TSCHUDI_CLOSEJOB TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__TSCHUDI_DELETED_MAIL TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__TSCHUDI_LIAB_REFRESH TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__TSCHUDI_MERC_PROBLEM TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__TSCHUDI_MERGRECORDS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__USER_AGRITEM_MES TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__USER_AGRITEM_MES_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__USER_BLITEM_MES TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__USER_BLITEM_MES_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__USER_QUOTA_MES TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__USER_QUOTA_MES_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__VOUCHER TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__VOYAGE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__VOYLEG TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_ACC_SYSTEM TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_ADD_C TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_ADD_D TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_ADD_I TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_ADD_I_X TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_ADD_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_ADD_N TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_ADD_S TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_ADD_T TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_ADD_U TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_ADD_W TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_CAT_RULE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_CAT_RULE_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_CLASS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_COLOR TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_COLOR_FRAGMENT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_COLOR_RULE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_COMPANY TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_COMP_OBJNAME TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_COUNTRY TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_DEPART TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_ERROR TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_ERROR_U TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_EXP_ID TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_FIELD TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_FIELD_SEQ_START TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_FILELIB TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_FORM TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_FORM_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_FORM_METHOD TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_HISTORY_DEL TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_HISTORY_DEL_STR TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_HISTORY_MERGE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_HISTORY_MERGE_ID TO SSPRO_EMPLOYEE;
    GRANT INSERT ON SSPRO.Z__Z_HISTORY_MERGE_STR TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_HISTORY_MOD1 TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_HISTORY_MOD_STR1 TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_ID TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_JOB_LOG TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_JOB_LOG_STR TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_KIND_LIST TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_KIND_TYPE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_LANG_NUMBERS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_LINK_COMP_FORM TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_LINK_COMP_MENU TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_LINK_COMP_PAR TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_LINK_OBJ_FIELDS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_LINK_OBJ_USER TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_LINK_REP_FIELDS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_LINK_REP_REP TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_LINK_USER_DEP_ACC TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_LINK_USER_MENU TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_LINK_USER_REP TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_LINK_USER_TABLE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_MEMPAR TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_MENUS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_METHOD TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_MET_OBJECT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_NOTES TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_NOTES_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_OBJECT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_OBJECT_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_OBJECT_NAMES TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_OBJECT_RIGHTS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_OBJPROPDEF TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_OBJ_PROP TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_OPROPLIST TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_PACKING TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_PARAMS_DEF TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_PARAMS_DEF_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_PARAMS_VAL TO SSPRO_EMPLOYEE;
    GRANT INSERT ON SSPRO.Z__Z_PORTS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_PRINT TO SSPRO_EMPLOYEE;
    GRANT INSERT ON SSPRO.Z__Z_PRINT_LOG TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_PROPERTY TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_PROPERTY_M TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z__Z_PROPKIND TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_PROPVAL TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_PROPVAL_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_REPORT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_REPORT_FIELD TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_REP_PICT TO SSPRO_EMPLOYEE;
    GRANT SELECT ON SSPRO.Z__Z_REP_UNICODE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_SUBST_FORM TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_TABINDEX TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_TABLE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_TAB_ARCRULE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_TEMP_RULE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_TIME_WORK TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_TRANSFER TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_TRANSFER_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_TRANS_ADDS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_TRANS_CATS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_TRANS_CLIENT TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_TRANS_CODES TO SSPRO_EMPLOYEE;
    GRANT INSERT ON SSPRO.Z__Z_TRANS_FIELDS TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_TRANS_FUNC TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_TRANS_SCENARIO TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_TRANS_SCENARIO_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_TRANS_TABLES TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_U16_MESSAGES TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_USER TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_USER_EMAIL TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_USER_MESSAGE TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_USER_MESSAGE_U TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_USER_RULES TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_USER_RULES_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_VCX_METHOD TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_VCX_NAMES TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_WORK_JOURNAL TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_WORK_RECORD TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z__Z_WORK_RECORD_M TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z___DEBUG TO SSPRO_EMPLOYEE;
    GRANT INSERT, SELECT ON SSPRO.Z___KILL TO SSPRO_EMPLOYEE;




  -- 9 Object Privileges for DISPATCH 
    GRANT EXECUTE ON SSPRO.SET_TRANSFER TO DISPATCH;
    GRANT EXECUTE ON SSPRO.USER_CONNECT TO DISPATCH;
    GRANT SELECT ON SSPRO.Z_COMPANY$ TO DISPATCH;
    GRANT SELECT ON SSPRO.Z_MAINJS TO DISPATCH;
    GRANT SELECT ON SSPRO.Z_MAINVCX TO DISPATCH;
    GRANT SELECT ON SSPRO.Z_PARAMS_DEF TO DISPATCH;
    GRANT SELECT ON SSPRO.Z_PARAMS_VAL$ TO DISPATCH;
    GRANT SELECT ON SSPRO.Z_USER TO DISPATCH;
    GRANT SELECT ON SSPRO.Z_USER_CONNECT TO DISPATCH;


    
    
    
  -- 7 System Privileges for SSPRO 
  GRANT CREATE ANY SEQUENCE TO SSPRO WITH ADMIN OPTION;
  GRANT CREATE SEQUENCE TO SSPRO WITH ADMIN OPTION;
  GRANT CREATE SESSION TO SSPRO WITH ADMIN OPTION;
  GRANT SELECT ANY SEQUENCE TO SSPRO WITH ADMIN OPTION;
  GRANT SELECT ANY TABLE TO SSPRO WITH ADMIN OPTION;
  GRANT UNLIMITED TABLESPACE TO SSPRO WITH ADMIN OPTION;
  GRANT CREATE TABLE TO SSPRO WITH ADMIN OPTION;
  -- 5 Object Privileges for SSPRO 
    GRANT EXECUTE ON DISPATCH.Z_AUTH TO SSPRO;
    GRANT DELETE, SELECT ON DISPATCH.Z_CHANNEL TO SSPRO;
    GRANT DELETE, SELECT ON DISPATCH.Z_LOGSTAT TO SSPRO;
    GRANT DELETE, INSERT, SELECT ON DISPATCH.Z_STATFILT TO SSPRO;
    GRANT EXECUTE ON SYS.DBMS_SESSION TO SSPRO;
    

    


  -- 5 Object Privileges for LAPRO 

    GRANT EXECUTE ON DISPATCH.Z_AUTH TO LAPRO;
    GRANT DELETE, INSERT, SELECT ON DISPATCH.Z_STATFILT TO LAPRO;
    GRANT EXECUTE ON LINERPRO.AUTH TO LAPRO;
    GRANT EXECUTE ON SSPRO.Z_SYS TO LAPRO;
    GRANT EXECUTE ON SYS.DBMS_SESSION TO LAPRO;

    
    
    
    
    
 begin dbms_stats.gather_schema_stats ( ownname=>'SSPRO' ); end; /
###


