NLS_LANG=AMERICAN_AMERICA.WE8MSWIN1252 >> /etc/profile.d/oracle.sh


CREATE TABLESPACE RMAN_DATA DATAFILE 
  '/storage/database/oracle/sn/rmandata1.dbf' SIZE 60M AUTOEXTEND OFF
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 32K
SEGMENT SPACE MANAGEMENT MANUAL;


CREATE TABLESPACE REPAIR_TS DATAFILE 
  '/storage/database/oracle/sn/REPAIR_TS.dbf' SIZE 200M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 32K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE EDI DATAFILE 
  '/storage/database/oracle/sn/edi.dbf' SIZE 7000M AUTOEXTEND ON NEXT 100M MAXSIZE 10240M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 32K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SHIPNET DATAFILE 
  '/storage/database/oracle/sn/SHIPNET_SHIPNET.dbf' SIZE 50M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 32K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TEMPORARY TABLESPACE TEMPORARY_DATA TEMPFILE 
  '/storage/database/oracle/sn/tempdata_SHIPNET.dbf' SIZE 145M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;




CREATE TABLESPACE MWS_DATA_01 DATAFILE 
  '/storage/database/oracle/sn/MWS_DATA_01_SHIPNET.DBF' SIZE 1048M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 32K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE MWS_IDX_01 DATAFILE 
  '/storage/database/oracle/sn/MWS_IDX_01_SHIPNET.DBF' SIZE 524M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 32K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SNACS_DATA DATAFILE 
  '/storage/database/oracle/sn/SNACS_DATA01_SHIPNET.DBF' SIZE 6000M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 32K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SNACS_INDEX DATAFILE 
  '/storage/database/oracle/sn/SNACS_INDEX01_SHIPNET.DBF' SIZE 2000M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 32K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SNAUDIT DATAFILE 
  '/storage/database/oracle/sn/SNAUDIT01_SHIPNET.DBF' SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 32K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SNIBS_DATA DATAFILE 
  '/storage/database/oracle/sn/SNIBS_DATA01_SHIPNET.DBF' SIZE 600M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 32K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE SNIBS_INDEX DATAFILE 
  '/storage/database/oracle/sn/SNIBS_INDEX01_SHIPNET.DBF' SIZE 300M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 32K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE SNSYS DATAFILE 
  '/storage/database/oracle/sn/SNSYS01_SHIPNET.DBF' SIZE 30M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 32K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


on source:
export NLS_LANG=AMERICAN_AMERICA.WE8MSWIN1252
exp "'/ as sysdba'"  FULL=yes compress=no feedback=1000 consistent=yes buffer=2000000 recordlength=64000 file=/db/export.dump log=/db/export.log


on dest:
export NLS_LANG=AMERICAN_AMERICA.WE8MSWIN1252
exp "'/ as sysdba'"  FULL=yes feedback=1000 buffer=2000000 recordlength=64000 file=/db/export.dump log=/db/export.log




export NLS_LANG=AMERICAN_AMERICA.WE8MSWIN1252

select * from nls_database_parameters where parameter='NLS_CHARACTERSET'; 

 begin dbms_stats.gather_schema_stats ( user ); end;
