alias srm='sudo /usr/bin/rm'
alias smcedit='sudo /usr/bin/mcedit'
alias svi='sudo /usr/bin/vi'
alias rev5_systemd='sudo /media/sysdata/rev5/techpool/ontology/management/rev5/helpers/systemd.sh '
alias rev5_install='sudo /media/sysdata/rev5/techpool/ontology/management/rev5/helpers/install.sh '
